### ISSUE TITLE
Soft lock in Dragon's Lair

### ISSUE THREAD

**Issue by Anopob** [DanzaG/TR2-Rando#106]
If you get unarmed during Dragon's Lair and get the Grenade Launcher, it only comes with 10 grenades, which isn't enough to kill the key holder and the dragon. I assume this may be true with some other weapons as well.

An easy fix is to just increase the number of grenades given, but this could make the weapon imbalanced in other levels, so I am not sure what fix is desired here.

Somewhat related: I was thinking about this problem as more features are getting added and randomized. For example, in Wreck of the Maria Doria, if you don't get a large before the end, doing the drop in the drained section could end up impossible (or basically impossible, since you would have to do the entire level damageless). I was wondering what is desired during these randomizations, whether that be "impossible situations are possible to be generated" or "everything should be casual-friendly" etc.

**Comment by lahm86** [comment]
It's possible to single out any level and adjust the logic for it, so when randomizing the items in a level we know whether or not that level removes weapons/ammo. So for Dragon's Lair, I think there are a few options.

* Allocate more ammo as you say for the randomized weapon. Maybe we need to work out the minimum required to get through the level for each weapon.
* Maybe add a second weapon, so the first would let you get through the first couple of rooms and the second could be somewhere before the dragon.
* Don't randomize the pistols at all if the level becomes unarmed, so it would always be guaranteed you'd get the pistols in the same spot.
* Exclude the level altogether from becoming unarmed.

Maybe an option for difficulty mode is needed somewhere to manage this and potentially other situations?

**Comment by DanzaG** [comment]
Firstly @Anopob good question about the kind of goal for rando. I would say that there is a priority to make it casual friendly. 

We can apply level specific fixes as @lahm86 mentioned. In DL we provide a minimum equipment necessary to complete the level. In doria, we can avoid the final area drain if there is a secret there or if it does get drain, we provide a large in the room prior to the drop thats always there.

And yes maybe now is the time to start thinking of a global difficulty level.
