### ISSUE TITLE
Barkhang Monastery bugged item location

### ISSUE THREAD

**Issue by Anopob** [DanzaG/TR2-Rando#138]
Item locations in room 19 should be in room 55 (as seen in Eycore's stream). Prayer wheels can spawn here and not be seen/obtained in either flipmap for some reason.

**Comment by DanzaG** [comment]
This should be fixed now, it seems some locations specified the alternate room (19) rather than the real room. If they are placed in alternate they dont spawn (afaik).

**Comment by DanzaG** [comment]
Will leave open just in case
