### ISSUE TITLE
Dragon can spawn multiple times

### ISSUE THREAD

**Issue by lahm86** [DanzaG/TR2-Rando#146]
Crossing the trigger for MarcoBartoli will spawn a second dragon if the first has been killed, which crashes the game. If it is still alive, Bartoli is triggered again but the engine seems to handle it and realise the dragon is already spawned. The trigger for Bartoli should have the OnlyOnce flag set as per DL.

**Comment by DanzaG** [comment]
Vanilla:

FD Index:2115
Count:1
------------
-Function:4 - Trigger

0x8004	1000 0000 0000 0100 
0x3E00	0011 1110 0000 0000 
0x0058	0000 0000 0101 1000 
0x005D	0000 0000 0101 1101 
0x005C	0000 0000 0101 1100 
0x8062	1000 0000 0110 0010

What needs to change:

FD Index:2115
Count:1
------------
-Function:4 - Trigger

0x8004	1000 0000 0000 0100 
**0x3F00**	0011 111**1** 0000 0000 
0x0058	0000 0000 0101 1000 
0x005D	0000 0000 0101 1101 
0x005C	0000 0000 0101 1100 
0x8062	1000 0000 0110 0010

Use "SetOneShot" on the FDEntry.
