### ISSUE TITLE
Savegame to big to fit in buffer on 1.3.1

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#155]
CATACOMBS.TR2

![image](https://user-images.githubusercontent.com/9203254/121248067-e0627600-c89a-11eb-8887-6ac61ea79da8.png)

![image](https://user-images.githubusercontent.com/9203254/121249062-12280c80-c89c-11eb-8df3-9383cf9997e5.png)

**Comment by lahm86** [comment]
UI screenshot looks like 1.3.0. Tested both 1.3.0 and 1.3.1 with these seeds and the error does appear with the older version, but not the latest release. See #149 - too much harpoon ammo is the cause.
