### ISSUE TITLE
Other TR version preparations

### ISSUE THREAD

**Issue by lahm86** [DanzaG/TR2-Rando#219]
- [x] Merge updates from TRGE for TR3 level editing.
- [x] Move randomizer settings out of TR2LevelRandomizer. Make a shared class for use between all versions.
- [x] Remove what are currently duplicated variables between TR2LevelRandomizer and the main randomizers - pass the shared settings object instead.
- [x] Move current resources into a TR2 folder - each version will have its own folder. Update corresponding randomizers with correct paths.
- [x] Add logic to the main controller to allow determining what functionality is availability for a given TR type.
- [x] Update UI to disable options for currently unsupported randomizer types.
- [x] Rebrand UI to remove specific references to TR2.
- [x] Change default settings in the UI (unarmed count, sunset count etc) so they are retrieved from the core.
- [x] Update solution/projects to rename relevant namespaces, folders etc from "TR2" to simply "TR".

**Comment by lahm86** [comment]
Some thoughts for things to wrap up before the initial TR3 release:

- [ ] Add further unarmed locations for each level (Jungle is complete, all others have 1 location only).
- [ ] Add UPV to levels that end up in Antarctica/RX-Tech sequence where applicable.
- [ ] If Cavern is out of sequence, remove Willard and re-assign the stone pickups as keys/puzzles/quest items; otherwise, picking up the stones will end the level, and if the stones are changed, Willard can't be killed.
- [ ] Implement SFX randomization to complete the Audio options.

**Comment by DanzaG** [comment]
Task 4 from above comment is now documented in #227 as a future enhancement. For now, it will just be trigger endings.
