### ISSUE TITLE
TR3 - Item Randomizer

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#243]
- [x] Type Rando
- [x] OneLimit
- [x] Positions
- [x] Key Items
- [ ] Ammo allocation based on enemy difficulty for unarmed levels

**Comment by lahm86** [comment]
Some thoughts on auto-generated item locations.

- Have a defined list of banned rooms per level - i.e. can't be reached without glitches
- Ignore any flipped rooms
- If randomizing secrets, ignore reward (final) room
- Ignore rooms that have no collisional portals (like 15 in Crash Site)
- For all others, scan every sector and:
	- Ignore if shared with any other entity (other than ones we're relocating)
	- Ignore if shared with a collidable static mesh (are there any that span multiple sectors?)
	- Ignore if inside a wall (`sector.Floor == -127 && sector.Ceiling == -127`)
	- Ignore if `RoomBelow != 255`
	- Ignore if slidey slope (`(BoxIndex & 0x7FF0) >> 4 == 2047`)
	- Scan FD:
		- Ignore if underwater current trigger (maybe lower strengths permitted)
		- Ignore if pickup trigger, maybe? Would avoid items ending up with secrets at least.
		- Ignore if FDKillLaraEntry

This should give us all tiles Lara can stand on (or swim to) I think. For those with slant or triangulation FD, we'd need to work out the suitable pickup point, but for flat sectors it could just default to centre-tile (although it could even be randomly placed within flat tiles).

The manual part would be going through each level and listing banned rooms. That's 2727 across the game. More preferable maybe than tens of thousands of individual locations to plot/validate. But of course it relies on the above rules being completely accurate. We could either have a utility to generate the JSON and load it in during randomization, or if the algorithm is reasonably fast, just eliminate the large JSON file. Perhaps there should be an exclusions file for anything that can't be covered with rules easily.

This is a list of non-flipped rooms for all levels.
[nonflippedrooms.json.txt](https://github.com/DanzaG/TR2-Rando/files/7575439/nonflippedrooms.json.txt)

**Comment by lahm86** [comment]
Progress for listing banned rooms and locations (for auto-generated locations):
- [x] Jungle
- [x] Ruins
- [x] Ganges
- [x] Kaliya
- [x] Coastal
- [x] Crash
- [x] Madubu
- [x] Puna
- [x] Thames
- [x] Aldwych
- [x] Lud's
- [x] City
- [x] Nevada
- [x] HSC
- [x] Area51
- [x] Antarctica
- [ ] RXTech
- [ ] Tinnos
- [ ] Chamber
- [ ] Hallows

Total valid locations so far: 18,720
