### ISSUE TITLE
Land enemies that are spawned in water are immediately killed

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#46]
How do we approach?
- Limit based on if room has water or not (only water enemies can be in water rooms and vice versa) - Problem with this is some water enemies actually work quite well on land (moray eels).
- Drain rooms of water in certain scenarios
- Can we make enemies immune to water?

**Comment by DanzaG** [comment]
Note: this still allows water creature to spawn on land. Worth investigating the effects of this, mainly:

1. Do any of the drains make it impossible to complete a level?
2. Do any of the drains make it impossible to get a secret?

**Comment by rr-** [comment]
>Can we make enemies immune to water?

It's possible with patching the .exe
