### ISSUE TITLE
Guns/Ammo cross level & Difficulty Adjustment

### ISSUE THREAD

**Issue by eycore1** [DanzaG/TR2-Rando#47]
- For example, attaining the grenade launcher in the Great Wall - making sure there is enough ammo available for that weapon pickup.
- Randomized weapon pickup in offshore rig instead of the pistols and making sure there is enough ammo to kill Kevin
- Randomized weapon pickup in Home Sweet Home
- Enemies in randomizer are harder, maybe add more health/ammo pickups?

**Comment by DanzaG** [comment]
Section 5.4 in TRosettaStone

**Comment by DanzaG** [comment]
To add to HSH:

1. Add the sprite tile to the Images16 array
2. Add a TRSpriteTexture to capture the weapon to insert
3. Add a TRSpriteSequence with NegativeLength of -1, Offset set ot index into the TRSpriteTexture array, and the SpriteID must match the Sprite entity ID (E.G. Shotgun is 136)

I assume the game resolves the EntityID and associates it with the matching SpriteSequence based on the ID specified in there.

Thx to Raildex YEP.
