### ISSUE TITLE
Environmental Randomization

### ISSUE THREAD

**Issue by eycore1** [DanzaG/TR2-Rando#49]
We will think of a list of potential/natural locations.

- Enemies in flooded areas can be replaced with water creatures e.g tiger spawn in great wall with a shark or scuba.
- Normal levers can be replaced with underwater levers vice versa.
- Need to check if land secrets/items are fine if flooded
- Need to check if unflooded areas can be navigated - areas of forced damage (medi nearby just incase?)
- How will the boat behave in venice?
- Should this be optional (tick/untick)?
- Home Sweet Home Daytime/night time - what other levels work?
- Invisible platforms?
- Can we change Floating Island texture colour e.g from green to blue?
- Change colour of the skidoo?

**Comment by eycore1** [comment]
Adding Danza's comment the other day on stream.

Flooding areas of the Great Wall (starting area at different levels all the way up to guard tower, first key area and trex pit)
Xian Lava
Diving area Acid
Tibet Boulders
Floating Islands flooded?? that might be interesting

**Comment by lahm86** [comment]
TODO list for level mirroring.

- [ ] Investigate TR2Box/overlaps as baddie AI is broken.
- [ ] Texture flipping needs improvement.
- [ ] Slopes with both X and Z slants need updating.
- [ ] Setting climbable values is buggy in FD. See RM81 in GW.
- [ ] Large static meshes (more than one tile) are awkward to reposition (room 7 in GW for example). Venice awnings trims need rotating. Dragons at start of Xian angled incorrectly.
- [ ] The camera in rooms 41/42 in GW seems to behave oddly. Occurs throughout the game, despite no camera triggers.
- [ ] Double doors will need swapped - see Venice.
- [ ] Underwater current directions.
- [ ] Enemies in 21 in 40F don't make any sounds?
- [ ] Check sound sources in general e.g. flames from chandelier room seem loud near level exit in Bartoli's.
- [ ] Tilt bridges need to be swapped.
- [ ] Rotate Marco Bartoli in DL.
- [ ] HSH starting cutscene is about 10 miles out.

**Comment by lahm86** [comment]
Ice Palace lava bowl needs to be rotated after mirroring.
