### ISSUE TITLE
Purple Barney in The Great Wall

### ISSUE THREAD

**Issue by eycore1** [DanzaG/TR2-Rando#72]
apel suggested this one

**Comment by Gizzy91** [comment]
Had a crack at this, unfortunately the T-Rex's leg and neck texture are shared with the under-side of him (Green texture in WALL.TR23.png) so it looks a little janky.

Pop the Tyrannosaur folder in TexturePacks/WALL

[Tyrannosaur.zip](https://github.com/DanzaG/TR2-Rando/files/5011472/Tyrannosaur.zip)

**Comment by DanzaG** [comment]
Added to texture packs
