### ISSUE TITLE
Cracker sometimes not dropping in dragon's lair

### ISSUE THREAD

**Issue by eycore1** [DanzaG/TR2-Rando#75]
Crit had an issue last night, where the cracker would not drop

Cracker drop - https://www.twitch.tv/videos/697340192?t=6h19m25s

No cracker - https://www.twitch.tv/videos/697340192?t=6h22m51s

**Comment by DanzaG** [comment]
@eycore1 is this the new version? it shouldn't happen anymore as this was covered in #65 If he randomized with V1.0 release and not V1.1bq then the bug will still be present

**Comment by eycore1** [comment]
this is the new version yeah

**Comment by DanzaG** [comment]
i think i see the issue, is it to do with grenade kill vs normal kill? grenade kill bypasses the jade anim. @eycore1

**Comment by DanzaG** [comment]
Either way ill have to investigate as this should not happen with #65 applied
