### ISSUE TITLE
Chicken ending the level

### ISSUE THREAD

**Issue by eycore1** [DanzaG/TR2-Rando#83]
Need to figure out a way to prevent this and only let it happen for the last chicken at the end. Especially if we are going to have enemies cross level in the future. Any way to trick the game into thinking it's a different object id?

**Comment by DanzaG** [comment]
@eycore1 i remember chreden mentioned something about essentially cloning an entity under a different type. But i need to see the level structure to see how it would work. The only problem is if we make it another ID how will the engine know the real behaviour?

**Comment by jw-dev** [comment]
I don't think this is possible. The end level behaviour is hardcoded into Control behaviour for the entity. In other words, if it "acts like" a big bird, it will end the level on death.

`void GiantYetiControl(sint16 item_number)
{
	if (item->hit_points <= 0)
	{
		if (item->frame_number == anims[item->anim_number].frame_end)
			level_complete = 1; // level is done when he is`

**Comment by DanzaG** [comment]
Big problem. Maybe we have some "special event" when implementing cross level enemies, where theres a small chance the level end trig is removed and we have a guardian fight in its place?

**Comment by DanzaG** [comment]
@jw-dev @eycore1 Have another idea, can we avoid that condition if we simply remove that death animation? if we can?

**Comment by DanzaG** [comment]
Raildex tested it and got it working via a animation trick, but then that stops big boi entirely from ending the level. Which we could alter with alternate endings. Other option is we change the hardcoded behaviour.

**Comment by rr-** [comment]
It can be fixed with a patch to the .exe.
