### ISSUE TITLE
Catacombs of Tailon - Bad Gold Secret Location

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#87]
Reported by ralee123 as being miles out of bounds, "1111111111" is the seed used

**Comment by Anopob** [comment]
Do you mean seed "111111111" (nine 1's)? Ten digits doesn't seem to be possible. Unfortunately, even with nine 1's, I was not able to replicate the bug, even with multiple randomization tries on unclean level files. I even tried manually using ten 1's just in case but I still couldn't get it.

However, this made me realize a bug with 10 digits in the new seed randomization. I'll make a fix for that.

**Comment by DanzaG** [comment]
I was provided 10 1s so i'm not sure. if you leave the seed blank it places every secret on the level, thats the next best check.

And yes I see, if you allow 10 digits you can exceed intmax

@Anopob

**Comment by eycore1** [comment]
I have fixed this along with 2 similar secrets in xian.  "IsInRoomSpace": false was missing
