### ISSUE TITLE
Cross-Level Enemies

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#97]
Implement the ability to spawn any enemy from any level.

**Comment by Raildex** [comment]
It would be nice to have some sort of Enemy Pool.
You have an interface that lists all enemies available in the game (+ skin variations)
Now the user can assign any combination of enemies to the levels (Ice Palace and Dragons Lair needing their respective bosses).

For example I want to assign T-Rex only to GW, which means that all enemies are T-Rexes.
Or I want Flamethrowers in Venice together with Scuba Steves.
